const PUBLIC_COURSES = [
  {
    id: 1,
    name: "Cuadernillo USICAMM 2026",
    desc: "Material de estudio impreso y digital con los temas clave del proceso USICAMM 2026. Elaborado por la Profa. Rocío, El Crack, el Profe Paco Ríos y la Mtra. Azalhia.",
    cat: "usicamm",
    catLabel: "USICAMM 2026",
    hours: "Autoaprendizaje",
    students: "—",
    rating: "5.0",
    price: "Consultar",
    badge: "",
    color: "linear-gradient(135deg,#1a3a5c,#2563a8)",
    icon: "CUA",
  },
  {
    id: 2,
    name: "Simulador USICAMM 2026",
    desc: "Practica con simulacros reales del examen USICAMM. Reactivos actualizados, tiempo cronometrado y retroalimentación inmediata para medir tu avance.",
    cat: "usicamm",
    catLabel: "USICAMM 2026",
    hours: "A tu ritmo",
    students: "—",
    rating: "5.0",
    price: "Consultar",
    badge: "hot",
    color: "linear-gradient(135deg,#c8952a,#e8b84b)",
    icon: "SIM",
  },
  {
    id: 3,
    name: "Plataforma de Estudio USICAMM 2026",
    desc: "Acceso completo a la plataforma web con contenido estructurado, videos, materiales descargables y seguimiento de tu progreso en tiempo real.",
    cat: "usicamm",
    catLabel: "USICAMM 2026",
    hours: "Acceso de por vida",
    students: "—",
    rating: "5.0",
    price: "Consultar",
    badge: "new",
    color: "linear-gradient(135deg,#1e6b45,#27ae60)",
    icon: "PLA",
  },
  {
    id: 4,
    name: "Plan Completo con Acompañamiento USICAMM 2026",
    desc: "Todo lo que necesitas en un solo plan: Cuadernillo + Simulador + Plataforma web + Sesiones en vivo + Resolución de dudas durante todo tu proceso. La opción más completa.",
    cat: "usicamm",
    catLabel: "USICAMM 2026",
    hours: "Sesiones en vivo incluidas",
    students: "—",
    rating: "5.0",
    price: "$1,499",
    oldPrice: "$3,000",
    badge: "top",
    color: "linear-gradient(135deg,#7c3aed,#a855f7)",
    icon: "COM",
  },
  {
    id: 5,
    name: "Acompañamiento a la Promoción Vertical 2026",
    desc: "El camino a tu Dirección o Supervisión empieza aquí. Domina el proceso de Promoción Vertical 2026 con EPAD. Incluye aspectos normativos, gestión escolar y vínculo con la comunidad.",
    cat: "usicamm",
    catLabel: "USICAMM 2026",
    hours: "Inicia 27 Abr 2026",
    students: "—",
    rating: "5.0",
    price: "$199 MXN",
    oldPrice: "$799 MXN",
    badge: "hot",
    color: "linear-gradient(135deg,#0a4a7a,#1a7abf)",
    icon: "AEP",
    recursos: [
      "Audio tipo podcast",
      "Grupo de WhatsApp",
      "Videos explicativos",
      "Resúmenes",
      "Presentaciones",
      "Simuladores",
    ],
  },
];

const TESTIMONIALS = [
  {
    text: "El simulador de EPAD me ayudó a prepararme con confianza. Aprobé el examen USICAMM a la primera. ¡Totalmente recomendado!",
    author: "María G.",
    role: "Docente de Primaria",
    stars: 5,
    color: "#1a3a5c",
  },
  {
    text: "Los materiales están muy bien estructurados y la atención del equipo es excepcional. Vale cada peso invertido.",
    author: "Carlos R.",
    role: "Maestro de Secundaria",
    stars: 5,
    color: "#c8952a",
  },
  {
    text: "Gracias a las planeaciones y recursos de EPAD pude organizarme mejor y obtener mejores resultados en mi grupo.",
    author: "Ana L.",
    role: "Maestra de Preescolar",
    stars: 5,
    color: "#1e6b45",
  },
  {
    text: "El acompañamiento personalizado marcó la diferencia. Sentí apoyo real en cada etapa del proceso.",
    author: "Roberto M.",
    role: "Docente de Bachillerato",
    stars: 5,
    color: "#7c3aed",
  },
  {
    text: "Excelente plataforma, muy intuitiva y completa. El contenido es claro y actualizado. Lo recomiendo al 100%.",
    author: "Laura P.",
    role: "Profesora de Telesecundaria",
    stars: 5,
    color: "#0a4a7a",
  },
  {
    text: "Con el cuadernillo y los simuladores logré superar mis expectativas. Un equipo que de verdad sabe de educación.",
    author: "Diego S.",
    role: "Docente de Primaria",
    stars: 5,
    color: "#b22222",
  },
];
